### PR TITLE
Rewritten parsing and execution algorithm

### PR DESCRIPTION
**Pull request by danielgindi**
This is a huge update.

1. Everything is 400% faster now.
2. Implemented tokenizer and expression tree,
   So tokenizing is now more clear and less prone to bugs,
   and the expression parsing into a tree of actions is much more clear.
3. The tree can also be reused for blazing-fast execution of same expression.

I have a few suggestions:
1. Maybe rename the branch to `master`, to conform to the standard? It's pretty confusing to do a checkout and receive an error that there's no `master` branch.
2. Now this is a big one... But... Maybe rename the library? :-) I'll explain:

I know that this was probably about allowing to evaluate basic expressions for special types that are not native, and I like the extension model where you can supply operators.
But now it supports much more than the basic operators, but actually a full set of logic, bitwise and basic math operators, supporting Strings, Booleans etc.
It's a library with a big added value on its own, even without the support for decimal.js.

I got into this because I looked at making something like this, without the complex recursive algorithms that makes adjusting the algorithms a giant mess. BigEval was a very good candidate, with builtin support for constants and calling functions. So I wanted to take that as the baseline and improve on that.
Now a person can parse Excel formulas with little adjustment, or execute logic and math expressions in a safe environment.

I need this in C# too. So I'll probably convert this to C# soon (And we'll need to think of what type I want to work with, `double`, `float` or `decimal`? Or maybe customizable?)
But it just won't make any sense calling it `BigEval.net`, the name does not imply what the library does :-)

### CODE REVIEW

**Comment by danielgindi** [comment]
Oh, and this closes #9 too

**Comment by aviaryan** [comment]
Hi @danielgindi . This PR looks exciting. I will review it soon. Can you please provide a reference to the parsing algorithm you have used (if possible) so that I can understand it better.

**Comment by danielgindi** [comment]
@aviaryan Oh I didn't use any existing one (that I know of). The existing ones that I've encountered are recursive, with a lot of chained return calls, which make it very hard to understand what's going on, or to control operation order etc.
Just written it as I go. 

I've put comments where I saw fit

**Comment by danielgindi** [comment]
I've completed porting to .net: https://github.com/danielgindi/Eval.net

**Comment by aviaryan** [comment]
@danielgindi The .NET port looks cool. 😄 Glad to see an implementation of BigEval in another language. 
BTW, I wanted to let you know that I am occupied for the coming 3-4 days and so will only be able to review this PR sometime later. Sorry for the delay.

**Pull request merged**
