### PR TITLE
Support for multi-char operands, bitwise, logical and comparisons (Closes #10)

### LINKED ISSUE #10: Support for logical operator?
How complicated would it be to add support for the logical OR and AND?
I basically want something like this: `X > 5 || (X < 2 && X > -3)`, to return `true` or `false`.

### PR DESCRIPTION
**Pull request by danielgindi**
While working on it, I made the operands always be passed as native values, instead of converting forth-and-back from string to number and number to string.

This makes it easier to add ops, to work with booleans, and faster to execute.

### CODE REVIEW

**Comment by aviaryan** [comment]
> While working on it, I made the operands always be passed as native values, instead of converting forth-and-back from string to number and number to string.
This makes it easier to add ops, to work with booleans, and faster to execute.

👍 

---

Great work @danielgindi 🎉⚡️
Unfortunately I can't merge this PR right now as some tests are failing. Please have a look.

**Comment by danielgindi** [comment]
I've updated the tests

**Comment by aviaryan** [comment]
@danielgindi Thanks for your work. This is really an exciting addition to BigEval.
However I found a bug with this expression. 
`-8&&13^1&2`
Answer should be 13 but right now bigeval gives NaN for it. 
Please have a look into it.
Also I suggest modifying tests/common.js to include new operands as it can help in finding lots of bugs.

**Comment by danielgindi** [comment]
Done :-)

**Comment by aviaryan** [comment]
> While working on it, I made the operands always be passed as native values, instead of converting forth-and-back from string to number and number to string.

Just one more thing @danielgindi , and it's my mistake, I should have let you know sooner that we shouldn't use operands as numbers in BigEval because it will not work with other big number libraries like decimal.js (see [README for decimal.js extension](https://github.com/aviaryan/BigEval.js#extending-with-big-number-libraries)).  This is one of the main objectives of BigEval so we can't drop it. 
Decimal.js extension will probably work for smaller numbers but for arbitrarily large numbers which are outside native JavaScript support, we will have issues. So BigEval should always handle numbers as strings i.e. the way it was before. 
Please incorporate this change so that I can merge this PR. 😄

**Comment by danielgindi** [comment]
Well, not necessarily. We can allow returning the alternative type in parseVar for extensions, and everything will continue to work as before with big numbers

**Comment by danielgindi** [comment]
Done! :-)

There's now an extra extension function called `number(str)` that returns the appropriate type for a supplied string. The extension demo with decimal.js has been updated.

**Comment by aviaryan** [comment]
Thanks for the PR. This would have indeed taken a lot of effort. 😊

**Comment by danielgindi** [comment]
You're welcome :-) Thanks for sharing your work!

**Pull request merged**
